name: workflows

services:
  laravel:
    image: workflows-dev
    build: .
    container_name: laravel
    ports: 
      - 80:80
    volumes:
      - .:/var/www/html
    depends_on: 
      - mysql

  node:
    image: node:gallium-alpine3.17
    container_name: node
    working_dir: /home/node/app
    ports:
      - 5173:5173
    volumes:
      - .:/home/node/app
    depends_on: 
      - laravel
    command: sh -c 'npm i && npm run dev'
    # command: sh -c 'npm i && npm run build && tail -f /dev/null'
    # command: tail -f /dev/null

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    environment: 
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_HOST=%
    ports: 
      - 3306:3306
    volumes: 
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: 